#!/usr/bin/env bash

set -eux

read -a ci_env <<<"$(bash <(curl -s https://codecov.io/env))"

. "$(realpath -- "$(dirname "${BASH_SOURCE[0]}")/../sources/run.sh")"
docker run "${ci_env[@]}" -e CI=true --name "toxcore-$BUILD" --rm -t "toxchat/c-toxcore:$BUILD" /usr/local/bin/codecov