#!/bin/sh

set -eux

. "$(realpath -- "$(dirname "${BASH_SOURCE[0]}")/../sources/run.sh")"

docker build -t "toxchat/c-toxcore:$BUILD-nginx" -f "$DOCKERDIR/nginx.Dockerfile" "$DOCKERDIR"
docker run --name "toxcore-$BUILD" --rm -it -p "28192:80" "toxchat/c-toxcore:$BUILD-nginx"
